"""init schema: 21 tables

Revision ID: 7d2910a0f7ca
Revises: 
Create Date: 2026-08-19 16:58:41.138879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2910a0f7ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('store_name', sa.String(length=100), server_default='上海旗舰店', nullable=False, comment='门店(本期固定上海旗舰店)'),
    sa.Column('appointment_date', sa.DateTime(), nullable=True, comment='预约到店时间'),
    sa.Column('intention', sa.String(length=200), nullable=True, comment='意向产品/系列'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='0待处理/1已联系/2已到店/3已关闭'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_phone'), 'appointment', ['phone'], unique=False)
    op.create_index(op.f('ix_appointment_status'), 'appointment', ['status'], unique=False)
    op.create_table('banner',
    sa.Column('image_url', sa.String(length=255), nullable=False, comment='图片地址'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='标题'),
    sa.Column('subtitle', sa.String(length=200), nullable=True, comment='副标题'),
    sa.Column('link_url', sa.String(length=255), nullable=True, comment='跳转链接'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_info',
    sa.Column('title', sa.String(length=150), nullable=False, comment='标题'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('space_tags', sa.JSON(), nullable=True, comment='空间标签数组'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='面积'),
    sa.Column('finished_at', sa.String(length=30), nullable=True, comment='完工时间'),
    sa.Column('content', sa.Text(), nullable=True, comment='项目介绍(富文本)'),
    sa.Column('images', sa.JSON(), nullable=True, comment='实景图集'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1发布/0下线'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('dept_name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级部门(自关联)'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_parent_id'), 'department', ['parent_id'], unique=False)
    op.create_table('faq',
    sa.Column('category', sa.String(length=50), nullable=True, comment='可选分类'),
    sa.Column('question', sa.String(length=300), nullable=False, comment='问题'),
    sa.Column('answer', sa.Text(), nullable=True, comment='答案(富文本)'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('title', sa.String(length=100), nullable=False, comment='职位名称'),
    sa.Column('category', sa.SmallInteger(), nullable=False, comment='1社会招聘/2校园招聘'),
    sa.Column('location', sa.String(length=100), server_default='上海', nullable=False, comment='工作地点'),
    sa.Column('job_type', sa.String(length=20), nullable=True, comment='全职/实习/校招'),
    sa.Column('salary_range', sa.String(length=50), nullable=True, comment='薪资范围'),
    sa.Column('responsibility', sa.Text(), nullable=True, comment='岗位职责(富文本)'),
    sa.Column('requirement', sa.Text(), nullable=True, comment='任职要求(富文本)'),
    sa.Column('contact', sa.String(length=200), nullable=False, comment='简历投递邮箱/联系方式'),
    sa.Column('is_urgent', sa.SmallInteger(), server_default='0', nullable=False, comment='1急招/0普通'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1招聘中/0已关闭'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_category'), 'job', ['category'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_table('message',
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('content', sa.Text(), nullable=False, comment='留言内容'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='0待处理/1已处理'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_phone'), 'message', ['phone'], unique=False)
    op.create_table('milestone_item',
    sa.Column('year', sa.String(length=10), nullable=False, comment='年份'),
    sa.Column('title', sa.String(length=150), nullable=True, comment='事件标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件说明'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序(时间倒序)'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_category',
    sa.Column('name', sa.String(length=50), nullable=False, comment='栏目名称'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_content',
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='类型标识(唯一)'),
    sa.Column('title', sa.String(length=150), nullable=True, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='富文本正文'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type')
    )
    op.create_table('product_category',
    sa.Column('name', sa.String(length=100), nullable=False, comment='系列名称'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序(小在前)'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_sort_order'), 'product_category', ['sort_order'], unique=False)
    op.create_table('store',
    sa.Column('name', sa.String(length=100), nullable=False, comment='门店名称'),
    sa.Column('city', sa.String(length=50), server_default='上海', nullable=False, comment='城市(本期固定上海)'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='地址'),
    sa.Column('phone', sa.String(length=50), nullable=False, comment='联系电话'),
    sa.Column('business_hours', sa.String(length=100), nullable=True, comment='营业时间'),
    sa.Column('longitude', sa.String(length=30), nullable=True, comment='经度(单店本期不填)'),
    sa.Column('latitude', sa.String(length=30), nullable=True, comment='纬度(单店本期不填)'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_config',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键(唯一)'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('sys_operation_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作人 → sys_user.id'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='模块，如 product'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='动作 create/update/delete/status/export/login'),
    sa.Column('detail', sa.String(length=500), nullable=True, comment='操作详情，如「下架产品：胡桃木餐桌」'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='来源 IP'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_operation_log_module'), 'sys_operation_log', ['module'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_user_id'), 'sys_operation_log', ['user_id'], unique=False)
    op.create_table('sys_permission',
    sa.Column('perm_code', sa.String(length=80), nullable=False, comment='权限码，如 product:edit'),
    sa.Column('perm_name', sa.String(length=80), nullable=True, comment='权限名称'),
    sa.Column('menu_key', sa.String(length=50), nullable=True, comment='关联后台菜单 key'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perm_code')
    )
    op.create_table('sys_role',
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称(唯一)'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='角色说明'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('job_application',
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='应聘职位 → job.id'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('resume_url', sa.String(length=255), nullable=False, comment='简历附件路径'),
    sa.Column('note', sa.Text(), nullable=True, comment='自我推荐/备注'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='0待处理/1已联系/2已淘汰/3已录用'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_application_job_id'), 'job_application', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_application_phone'), 'job_application', ['phone'], unique=False)
    op.create_table('news_article',
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='所属栏目 → news_category.id'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图 URL'),
    sa.Column('summary', sa.String(length=300), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文(富文本已清洗)'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='来源(转载标注)'),
    sa.Column('is_published', sa.SmallInteger(), server_default='0', nullable=False, comment='1已发布/0未发布'),
    sa.Column('is_top', sa.SmallInteger(), server_default='0', nullable=False, comment='1置顶/0否'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_article_category_id'), 'news_article', ['category_id'], unique=False)
    op.create_index(op.f('ix_news_article_is_published'), 'news_article', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_article_is_top'), 'news_article', ['is_top'], unique=False)
    op.create_index(op.f('ix_news_article_publish_time'), 'news_article', ['publish_time'], unique=False)
    op.create_table('product',
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='所属系列 → product_category.id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('series', sa.String(length=50), nullable=True, comment='所属系列，如「胡桃禮」'),
    sa.Column('product_no', sa.String(length=50), nullable=False, comment='产品编号(唯一)'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品描述(富文本已清洗)'),
    sa.Column('specs', sa.JSON(), nullable=True, comment='规格参数 JSON'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图 URL'),
    sa.Column('images', sa.JSON(), nullable=True, comment='其它图片 URL JSON 数组'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='0草稿/1上架/2下架'),
    sa.Column('is_top', sa.SmallInteger(), server_default='0', nullable=False, comment='1首页推荐/0否'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序(越大越靠前)'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_is_top'), 'product', ['is_top'], unique=False)
    op.create_index(op.f('ix_product_product_no'), 'product', ['product_no'], unique=True)
    op.create_index(op.f('ix_product_status'), 'product', ['status'], unique=False)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID → sys_role.id'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限点 ID → sys_permission.id'),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名(唯一)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='性别 0未知/1男/2女'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='岗位'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门 → department.id'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 → sys_role.id'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('must_change_pwd', sa.Boolean(), server_default='1', nullable=False, comment='首次登录强制改密'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_sys_user_dept_id'), 'sys_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_dept_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_product_status'), table_name='product')
    op.drop_index(op.f('ix_product_product_no'), table_name='product')
    op.drop_index(op.f('ix_product_is_top'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_news_article_publish_time'), table_name='news_article')
    op.drop_index(op.f('ix_news_article_is_top'), table_name='news_article')
    op.drop_index(op.f('ix_news_article_is_published'), table_name='news_article')
    op.drop_index(op.f('ix_news_article_category_id'), table_name='news_article')
    op.drop_table('news_article')
    op.drop_index(op.f('ix_job_application_phone'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_job_id'), table_name='job_application')
    op.drop_table('job_application')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_operation_log_user_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_module'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_table('sys_config')
    op.drop_table('store')
    op.drop_index(op.f('ix_product_category_sort_order'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_table('page_content')
    op.drop_table('news_category')
    op.drop_table('milestone_item')
    op.drop_index(op.f('ix_message_phone'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_category'), table_name='job')
    op.drop_table('job')
    op.drop_table('faq')
    op.drop_index(op.f('ix_department_parent_id'), table_name='department')
    op.drop_table('department')
    op.drop_table('case_info')
    op.drop_table('banner')
    op.drop_index(op.f('ix_appointment_status'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_phone'), table_name='appointment')
    op.drop_table('appointment')
    # ### end Alembic commands ###
